### PR TITLE
Migrate from Glide to dep

### PR DESCRIPTION
**Pull request by vhugo**
Hi @robertoduessmann 

saw that you're using Glide, [according to them](https://github.com/Masterminds/glide#golang-dep), they suggest migrating to dep. You didn't ask for it, but I would like to help out with this PR. 😉

### CODE REVIEW

**Comment by robertoduessmann** [comment]
Hi @vhugo, thanks for interest in improve project :grinning: 

This is a great point, I've saw many projects migrating to dep.
I only have one consideration... In the beginning, I've added glide because I host the app on [Heroku](https://www.heroku.com/), and according some guides, I read that glide is a good option to run the app there (https://devcenter.heroku.com/articles/go-dependencies-via-glide).

Do you know if heroku and another Go hosts are ready to work with dep?

Thanks again for your help.

**Comment by vhugo** [comment]
Hi @robertoduessmann 

In the docs for the Heroku Go Buildpack, it says that it is supported (https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-go) , to be honest, I never deployed a Go application to Heroku, but this doc in the repo has been [updated recently with dep info](https://github.com/heroku/heroku-buildpack-go/commit/773a51fab23f113a0242bd31292ff6ba5e8c9751). 

I guess you should not have problems with that, but then again I've never done it, so I highly recommend some further tests. 😉

**Comment by robertoduessmann** [comment]
That's look good @vhugo , according docs, isn't be expect any problem. :rocket: 

I will merge the migration and I will test if app is ok.
If I have problems, I come back to use glide, ok?

**Comment by robertoduessmann** [comment]
It's running @vhugo :tada: :rocket: 
I just had a problem with https://github.com/robertoduessmann/weather-api/pull/13, but after I fixed the app is running perfectly at Heroku.

Thanks @vhugo

**Comment by vhugo** [comment]
Nicely done, @robertoduessmann.  Glad to help.

**Pull request merged**
